fix NoClassDefFoundError
Kotlin accounts.keys is using
ConcurrentHashMap.keySet()
which is only available with API24

Kotlin accounts.keys() uses
ConcurrentHashMap.keys()
which is available with all our supported APIs